=== lfkimura/cursos/java-com-xml/src/venda.xsd
<?xml version="1.0" encoding="UTF-8"  ?>
<schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
	<xsd:element name="venda">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="formaDePagamento" type="string" />
				<xsd:element name="produtos">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="produto" maxOccurs="unbounded"/>

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="moeda" type="string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="produto">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="nome" type="string" />
				<xsd:element name="preco" type="double" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</schema>

=== lfkimura/cursos/java-com-xml/src/venda.xml
<?xml version="1.0" encoding="UTF-8"?>
<venda moeda="real" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="venda.xsd" >
<formaDePagamento>Cart√£o</formaDePagamento>
<produtos>
	<produto>
		<nome>Agua</nome>
		<preco>10.00</preco>
	</produto>	
	<produto>
		<nome>arroz</nome>
		<preco>3.00</preco>
	</produto>

</produtos>
</venda>
